export interface SlopRule {
  name: string
  re: RegExp
}

// Hard bans: AI-vocabulary spikes, filler intensifiers, banned phrases.
// Applied to every source file, so keep the list to prose-only words that
// cannot collide with identifiers or property values.
const WORDS: [RegExp, string][] = [
  [/\bdelv(e|es|ed|ing)\b/i, 'delve'],
  [/\btapestry\b/i, 'tapestry'],
  [/\btestament\b/i, 'testament'],
  [/\bunderscor(e|es|ed|ing)\b/i, 'underscore'],
  [/\bshowcas(e|es|ed|ing)\b/i, 'showcase'],
  [/\brealm\b/i, 'realm'],
  [/\bboasts?\b/i, 'boast'],
  [/\bmeticulous(ly)?\b/i, 'meticulous'],
  [/\bmultifaceted\b/i, 'multifaceted'],
  [/\bgarners?(ed)?\b/i, 'garner'],
  [/\bbolsters?(ed)?\b/i, 'bolster'],
  [/\bvibrant\b/i, 'vibrant'],
  [/\bpivotal\b/i, 'pivotal'],
  [/\bparamount\b/i, 'paramount'],
  [/\bfosters?(ed|ing)?\b/i, 'foster'],
  [/\bembarks?(ed|ing)?\b/i, 'embark'],
  [/\bever-evolving\b/i, 'ever-evolving'],
  [/\bjourney\b/i, 'journey'],
  [/\bharness(es|ed|ing)?\b/i, 'harness'],
  [/\bleverag(e|es|ed|ing)\b/i, 'leverage'],
  [/\butiliz(e|es|ed|ing|ation)\b/i, 'utilize'],
  [/\belevat(e|es|ed|ing|ion)\b/i, 'elevate'],
  [/\bempowers?(ed|ing)?\b/i, 'empower'],
  [/\bunlocks?(ed|ing)?\b/i, 'unlock'],
  [/\bsupercharg(e|es|ed|ing)\b/i, 'supercharge'],
  [/\bunleash(es|ed|ing)?\b/i, 'unleash'],
  [/\bgame-chang(er|ing)\b/i, 'game-changer'],
  [/\brevolution(ize|ary|ized|izing)\b/i, 'revolutionize'],
  [/\bstreamlin(e|es|ed|ing)\b/i, 'streamline'],
  [/\bseamless(ly)?\b/i, 'seamless'],
  [/\beffortless(ly)?\b/i, 'effortless'],
  [/\brobust\b/i, 'robust'],
  [/\bholistic\b/i, 'holistic'],
  [/\bsynerg(y|ies)\b/i, 'synergy'],
  [/\bcomprehensive\b/i, 'comprehensive'],
  [/\bcutting-edge\b/i, 'cutting-edge'],
  [/\bstate-of-the-art\b/i, 'state-of-the-art'],
  [/\bgroundbreaking\b/i, 'groundbreaking'],
  [/\binnovative\b/i, 'innovative'],
  [/\bworld-class\b/i, 'world-class'],
  [/\bbest-in-class\b/i, 'best-in-class'],
  [/\benterprise-grade\b/i, 'enterprise-grade'],
  [/\bproduction-ready\b/i, 'production-ready'],
  [/\bend-to-end\b/i, 'end-to-end'],
  [/\bblazingly\b/i, 'blazingly'],
  [/\bplethora\b/i, 'plethora'],
  [/\bmyriad\b/i, 'myriad'],
  [/\bnestled\b/i, 'nestled'],
  [/\bmoreover\b/i, 'moreover'],
  [/\bfurthermore\b/i, 'furthermore'],
  [/\blandscape\b/i, 'landscape'],
  [/\bnavigat(e|es|ed|ing)\b/i, 'navigate'],
  [/\bincredibly\b/i, 'incredibly'],
  [/\bgenuinely\b/i, 'genuinely'],
  [/\bmind-blow(ing|n)\b/i, 'mind-blowing'],
]

export const BANNED_WORDS: SlopRule[] = WORDS.map(([re, name]) => ({ re, name }))

const PHRASES: [RegExp, string][] = [
  [/in today's/i, "in today's"],
  [/whether you('re| need| want)/i, 'whether you are'],
  [/look no further/i, 'look no further'],
  [/the future (of|is here)/i, 'the future of'],
  [/say (goodbye|hello) to/i, 'say goodbye/hello to'],
  [/trusted by/i, 'trusted by'],
  [/possibilities are endless/i, 'possibilities are endless'],
  [/it('s| is) worth (noting|mentioning)/i, 'worth noting'],
  [/here's the thing/i, "here's the thing"],
  [/the best part/i, 'the best part'],
  [/what if i told you/i, 'what if I told you'],
  [/imagine a world/i, 'imagine a world'],
  [/sound familiar/i, 'sound familiar'],
  [/are you ready to/i, 'are you ready'],
  [/ready to transform/i, 'ready to transform'],
  [/most people don't/i, "most people don't"],
  [/(^|\s)(meet|enter):/i, 'Meet:/Enter: intro'],
  [/changes everything/i, 'changes everything'],
  [/(thrilled|excited|humbled|delighted|proud) to (announce|share)/i, 'thrilled to announce'],
  [/in conclusion/i, 'in conclusion'],
  [/long story short/i, 'long story short'],
  [/paradigm shift/i, 'paradigm shift'],
  [/low-hanging fruit/i, 'low-hanging fruit'],
  [/commitment to excellence/i, 'commitment to excellence'],
  [/at its core/i, 'at its core'],
  [/at the end of the day/i, 'at the end of the day'],
  [/when it comes to/i, 'when it comes to'],
  [/designed to help you/i, 'designed to help you'],
  [/deep dive/i, 'deep dive'],
  [/dive into/i, 'dive into'],
  [/all-in-one/i, 'all-in-one'],
  [/a (wide|vast|diverse) array of/i, 'a wide array of'],
  [/treasure trove/i, 'treasure trove'],
  [/hidden gem/i, 'hidden gem'],
  [/one-stop/i, 'one-stop'],
  [/hassle-free/i, 'hassle-free'],
  [/peace of mind/i, 'peace of mind'],
  [/take your .{1,30} to the next level/i, 'next level'],
  [/unlock the power of/i, 'unlock the power of'],
  [/it's not just/i, "it's not just"],
]

export const BANNED_PHRASES: SlopRule[] = PHRASES.map(([re, name]) => ({ re, name }))

// Structural tells: punctuation, rhetorical patterns, significance tack-ons.
export const BANNED_STRUCTURES: SlopRule[] = [
  { re: /[‐-―]/, name: 'em/en dash (use a comma or period)' },
  { re: /[‘’“”]/, name: 'curly quotes (use ASCII quotes)' },
  { re: /[←-⇿➡]/, name: 'unicode arrow (use an icon)' },
  {
    re: /[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE0F}]/u,
    name: 'emoji',
  },
  {
    re: /\bNo [^.\n]{1,40}\.\s*No [^.\n]{1,40}\.\s*(Just|Only)\b/,
    name: 'No X. No Y. Just Z. pattern',
  },
  {
    re: /,\s*(highlight|underscor|emphasiz|ensur|reflect|symboliz|demonstrat|showcas|contribut|reinforc|represent|signal)ing\b/i,
    name: 'participial tack-on (", highlighting")',
  },
  {
    re: /\b(it'?s|this is|that'?s) not\b[^.!?]{0,80}\bit'?s\b/i,
    name: 'negative parallelism ("It is not X. It is Y.")',
  },
  {
    re: /!\s*[A-Z"']/,
    name: 'exclamation marks',
  },
]
